env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  arrow-parens: [error, as-needed]
  object-curly-spacing: [error, never]
  no-console: off
  max-len: [warn, {code: 80}]
